---
name: Ansible Lint

on:
  push:
    paths:
      - "ansible/**"
      - ".github/workflows/ci-ansible.yaml"
  pull_request:
    paths:
      - "ansible/**"
      - ".github/workflows/ci-ansible.yaml"
  workflow_dispatch:

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ansible-core and ansible-lint
        run: pip install ansible-core ansible-lint

      - name: Run ansible-lint
        run: ansible-lint ansible/
